sp:
  user-service:
    users: "[{\"id\":1,\"userName\":\"username-1\",\"password\":\"password-1\"},{\"id\":2,\"userName\":\"username-2\",\"password\":\"password-2\"},{\"id\":3,\"userName\":\"username-3\",\"password\":\"password-3\"}]"


spring:
  application:
    name: user-service
server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
