sp:
  user-service:
    users: "[{\"id\":1,\"userName\":\"用户1\",\"password\":\"密码1\"},{\"id\":2,\"userName\":\"用户2\",\"password\":\"密码2\"},{\"id\":3,\"userName\":\"用户3\",\"password\":\"密码3\"}]"


spring:
  application:
    name: user-service
server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
